### ISSUE TITLE
“nuScenes -> KITTI TASK” definition

### ISSUE THREAD

**Issue by wanghangege** [WoodwindHu/DTS#1]
Hello, I am a new entrant. I would like to inquire about the basic issues of domain migration, which (“nuScenes -> KITTI TASK” ) refers to the results of model trained on the nuScences datasets and just tested in KITTI datasets (test split) ?

**Comment by wanghangege** [comment]
In addition,  the mian funtion in "https://github.com/WoodwindHu/DTS/blob/main/pcdet/datasets/kitti/kitti_beam_id.py":
`
if __name__=='__main__':
    args = parse_config()
    for i in tqdm.tqdm(range(7518)):
        get_beam_id(os.path.join(args.data_path, "training/velodyne"), i)
`
the '7518' is the total number of test split, fuction " get_beam_i" use the trained velodyne to get beam, Why?

**Comment by WoodwindHu** [comment]
> Hello, I am a new entrant. I would like to inquire about the basic issues of domain migration, which (“nuScenes -> KITTI TASK” ) refers to the results of model trained on the nuScences datasets and just tested in KITTI datasets (test split) ?

We follow the setup of ST3D to test KITTI in val split

**Comment by WoodwindHu** [comment]
> In addition, the mian funtion in "https://github.com/WoodwindHu/DTS/blob/main/pcdet/datasets/kitti/kitti_beam_id.py": `if __name__=='__main__': args = parse_config() for i in tqdm.tqdm(range(7518)): get_beam_id(os.path.join(args.data_path, "training/velodyne"), i)` the '7518' is the total number of test split, fuction " get_beam_i" use the trained velodyne to get beam, Why?

sorry for the confusion, the code means to get beams for training set.
