### ISSUE TITLE
the pretrained model

### ISSUE THREAD

**Issue by ZSA010807** [WoodwindHu/DTS#14]
could you provide the pretrained model of PVRCNN on the waymo ?thank you

**Comment by WoodwindHu** [comment]
Hello, we could not provide the above pretrained models due to Waymo Dataset License Agreement, but you should achieve similar performance by training with the default configs.

**Comment by ZSA010807** [comment]
> Hello, we could not provide the above pretrained models due to Waymo Dataset License Agreement, but you should achieve similar performance by training with the default configs.
ok， thank you
