### ISSUE TITLE
About Drawing Software

### ISSUE THREAD

**Issue by lloveapple** [WoodwindHu/DTS#5]
Thank you very much for your excellent work. I am a first-year graduate student. I would like to ask what software is used to draw the main network architecture diagram (algorithm flow chart) in your thesis. I want to learn this software,  I believe learning to use such a tool would greatly benefit my ongoing studies and research. thank you very much !
good luck!

**Comment by WoodwindHu** [comment]
PowerPoint :D

**Comment by lloveapple** [comment]
okay thanks for your quick reply.
good luck!
